# Generated by Django 3.2.16 on 2022-11-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221029_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='Contact',
            name='email',
            field=models.CharField(default='email not provided', max_length=122),
            preserve_default=False,
        ),
    ]
