# Generated by Django 3.2.16 on 2022-11-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Contact',
            name='email',
        ),
    ]
