# Generated by Django 3.2.16 on 2022-11-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='email not provided', max_length=122),
            preserve_default=False,
        ),
    ]
