# Generated by Django 3.2.16 on 2022-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='answer',
            new_name='solution',
        ),
        migrations.AddField(
            model_name='contact',
            name='obtained_marks',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='q_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='t_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='total_marks',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
