# Generated by Django 3.2.16 on 2022-11-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_questions_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='solution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
